<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="geohabnet">
<title>Analyzing risk index using cropland connectivity • geohabnet</title>
<!-- favicons --><link rel="icon" type="image/png" sizes="16x16" href="../favicon-16x16.png">
<link rel="icon" type="image/png" sizes="32x32" href="../favicon-32x32.png">
<link rel="apple-touch-icon" type="image/png" sizes="180x180" href="../apple-touch-icon.png">
<link rel="apple-touch-icon" type="image/png" sizes="120x120" href="../apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" type="image/png" sizes="76x76" href="../apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" type="image/png" sizes="60x60" href="../apple-touch-icon-60x60.png">
<script src="../deps/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="../deps/bootstrap-5.2.2/bootstrap.min.css" rel="stylesheet">
<script src="../deps/bootstrap-5.2.2/bootstrap.bundle.min.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- bootstrap-toc --><script src="https://cdn.jsdelivr.net/gh/afeld/bootstrap-toc@v1.0.1/dist/bootstrap-toc.min.js" integrity="sha256-4veVQbu7//Lk5TSmc7YV48MxtMy98e26cf5MrgZYnwo=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- search --><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- pkgdown --><script src="../pkgdown.js"></script><meta property="og:title" content="Analyzing risk index using cropland connectivity">
<meta property="og:description" content="geohabnet">
<meta property="og:image" content="/logo.png">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <a href="#main" class="visually-hidden-focusable">Skip to contents</a>
    

    <nav class="navbar fixed-top navbar-light navbar-expand-lg bg-light"><div class="container">
    
    <a class="navbar-brand me-2" href="../index.html">geohabnet</a>

    <small class="nav-text text-muted me-auto" data-bs-toggle="tooltip" data-bs-placement="bottom" title="">1.0.0</small>

    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div id="navbar" class="collapse navbar-collapse ms-3">
      <ul class="navbar-nav me-auto">
<li class="nav-item">
  <a class="nav-link" href="../reference/index.html">Reference</a>
</li>
<li class="active nav-item dropdown">
  <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true" id="dropdown-articles">Articles</a>
  <div class="dropdown-menu" aria-labelledby="dropdown-articles">
    <a class="dropdown-item" href="../articles/analysis.html">Analyzing risk index using cropland connectivity</a>
    <a class="dropdown-item" href="../articles/distance_strategy.html">Distance Strategy</a>
    <a class="dropdown-item" href="../articles/global_analysis.html">Global Analysis</a>
    <a class="dropdown-item" href="../articles/Using-raster-file.html">Using raster file</a>
  </div>
</li>
<li class="nav-item">
  <a class="nav-link" href="../news/index.html">Changelog</a>
</li>
      </ul>
<form class="form-inline my-2 my-lg-0" role="search">
        <input type="search" class="form-control me-sm-2" aria-label="Toggle navigation" name="search-input" data-search-index="../search.json" id="search-input" placeholder="Search for" autocomplete="off">
</form>

      <ul class="navbar-nav">
<li class="nav-item">
  <a class="external-link nav-link" href="https://github.com/GarrettLab/CroplandConnectivity/" aria-label="github">
    <span class="fab fa fab fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>

    
  </div>
</nav><div class="container template-article">




<div class="row">
  <main id="main" class="col-md-9"><div class="page-header">
      <img src="../logo.png" class="logo" alt=""><h1>Analyzing risk index using cropland connectivity</h1>
                        <h4 data-toc-skip class="author">Krishna
Keshav(<a href="mailto:kkeshav@ufl.edu" class="email">kkeshav@ufl.edu</a>)</h4>
            
            <h4 data-toc-skip class="date">09 October, 2023</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/GarrettLab/CroplandConnectivity/blob/HEAD/vignettes/analysis.Rmd" class="external-link"><code>vignettes/analysis.Rmd</code></a></small>
      <div class="d-none name"><code>analysis.Rmd</code></div>
    </div>

    
    
<div class="section level2">
<h2 id="abstract">Abstract<a class="anchor" aria-label="anchor" href="#abstract"></a>
</h2>
<p>The network and connectivity of cropland can be used to analyse the
potential spread of plant pathogen. While network plays a crucial role,
there are several other factors that affects the spread and thus the
connectivity. Although croplands may be geographically connected, the
risk cannot be generalized as pathogen may not spread if it’s exclusive
to specific crop. <em>geohabnet</em> supports up to 10 parameters that
has potential to impact risk and connectivity among croplands. The
implementation is expanded upon <span class="citation">(Xing et al.
2020)</span>, which discusses global cropland connectivity. This
framework uses default values from the paper at the same time making
them as parameters and eventually turning it into framework for the
analysis of crops.</p>
<p>Although this article is focused on usage, it is useful to know for
interested developers that package design is inspired from widely used
Configuration-based design in software development <span class="citation">(Majors 2022)</span>, <span class="citation">(Nash and
DeMore 2009)</span>, and <span class="citation">(Allaire 2023)</span>
provides a text based interface to control the parameters values for
risk analysis in this context.</p>
<p>Primary objective of this vignette is to help user in getting
started, list capabilities and intuition behind them. It also describes
underlying implementation at high level to support the intuition behind
functions. Throughout the article, we will citing external sites and
resources which is relevant to usage of this package.</p>
<div class="section level3">
<h3 id="pre-requisites">Pre-requisites<a class="anchor" aria-label="anchor" href="#pre-requisites"></a>
</h3>
<div class="section level4">
<h4 id="definitions">Definitions<a class="anchor" aria-label="anchor" href="#definitions"></a>
</h4>
<ul>
<li><p>Raster - Raster is a digital encoding of 2D digital image with
underlying pixels as underlying. It also encapsulates other details like
resolution, dimensions etc which is useful in identification and
processing. Here, we use raster to represent maps.</p></li>
<li><p>TIFF(Tag Image File Format) is a file that stores raster and
information.</p></li>
</ul>
</div>
<div class="section level4">
<h4 id="external-materials">External materials<a class="anchor" aria-label="anchor" href="#external-materials"></a>
</h4>
<ul>
<li><p>Download and install R, R Studio - <a href="https://rstudio-education.github.io/hopr/starting.html" class="external-link uri">https://rstudio-education.github.io/hopr/starting.html/</a></p></li>
<li><p>Rasters - <a href="https://www.adobe.com/creativecloud/file-types/image/raster.html" class="external-link uri">https://www.adobe.com/creativecloud/file-types/image/raster.html</a></p></li>
<li><p>TIFF - <a href="https://www.adobe.com/creativecloud/file-types/image/raster/tiff-file.html" class="external-link uri">https://www.adobe.com/creativecloud/file-types/image/raster/tiff-file.html/</a></p></li>
</ul>
</div>
</div>
<div class="section level3">
<h3 id="datasets">Datasets<a class="anchor" aria-label="anchor" href="#datasets"></a>
</h3>
<p>We use publicly available sources to obtain crop information -</p>
<ul>
<li><p><a href="http://www.earthstat.org/harvested-area-yield-175-crops/" class="external-link">Monfreda</a>
<span class="citation">(Monfreda, Ramankutty, and Foley
2008)</span></p></li>
<li><p><a href="https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/PRFF8V" class="external-link">MapSpam
(2005)</a> <span class="citation">(International Food Policy Research
Institute 2019)</span></p></li>
</ul>
<p>Geodata provides set of APIs to access these datasets. For
visualization and plots, we use <a href="https://docs.ropensci.org/rnaturalearth/" class="external-link">rnaturalearth</a>.</p>
</div>
<div class="section level3">
<h3 id="quick-start">Quick Start<a class="anchor" aria-label="anchor" href="#quick-start"></a>
</h3>
<div class="section level4">
<h4 id="meta-information">Meta information<a class="anchor" aria-label="anchor" href="#meta-information"></a>
</h4>
<ul>
<li>Package documentation - <a href="http://geohab-site.s3-website.us-east-2.amazonaws.com/docs/" class="external-link uri">http://geohab-site.s3-website.us-east-2.amazonaws.com/docs/</a>
</li>
<li>Source code - <a href="https://github.com/GarrettLab/CroplandConnectivity/tree/main/geohabnet/" class="external-link uri">https://github.com/GarrettLab/CroplandConnectivity/tree/main/geohabnet/</a>
</li>
<li>Report issues - <a href="https://github.com/GarrettLab/CroplandConnectivity/issues/" class="external-link uri">https://github.com/GarrettLab/CroplandConnectivity/issues/</a>
</li>
<li>Lab website - <a href="https://www.garrettlab.com/" class="external-link uri">https://www.garrettlab.com/</a>
</li>
</ul>
</div>
<div class="section level4">
<h4 id="installation-and-loading">Installation and loading<a class="anchor" aria-label="anchor" href="#installation-and-loading"></a>
</h4>
<p>Installing <code>geohabnet</code> will also install its dependencies.
Please see the list of dependencies using
<code>desc::desc(package = "geohabnet")</code></p>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw">if</span> <span class="op">(</span><span class="op">!</span><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">require</a></span><span class="op">(</span><span class="st"><a href="https://devtools.r-lib.org/" class="external-link">"devtools"</a></span><span class="op">)</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html" class="external-link">install.packages</a></span><span class="op">(</span><span class="st">"devtools"</span><span class="op">)</span></span>
<span><span class="op">}</span></span></code></pre></div>
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="st"><a href="https://devtools.r-lib.org/" class="external-link">"devtools"</a></span><span class="op">)</span></span>
<span></span>
<span><span class="kw">if</span> <span class="op">(</span><span class="op">!</span><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">require</a></span><span class="op">(</span><span class="st"><a href="http://geohab-site.s3-website.us-east-2.amazonaws.com/docs/" class="external-link">"geohabnet"</a></span><span class="op">)</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="fu"><a href="https://remotes.r-lib.org/reference/install_github.html" class="external-link">install_github</a></span><span class="op">(</span><span class="st">"GarrettLab/CroplandConnectivity"</span>, subdir <span class="op">=</span> <span class="st">"geohabnet"</span><span class="op">)</span></span>
<span><span class="op">}</span></span></code></pre></div>
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="va"><a href="http://geohab-site.s3-website.us-east-2.amazonaws.com/docs/" class="external-link">geohabnet</a></span><span class="op">)</span></span></code></pre></div>
<p>At any point, access the help page using following -</p>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="op">?</span><span class="va">geohabnet</span></span>
<span><span class="co"># and</span></span>
<span><span class="op">?</span><span class="fu">geohabnet</span><span class="fu">::</span><span class="va"><a href="../reference/sean.html">sean</a></span> <span class="co"># any function</span></span></code></pre></div>
</div>
<div class="section level4">
<h4 id="run-analysis-on-default-configuration">Run analysis on default configuration<a class="anchor" aria-label="anchor" href="#run-analysis-on-default-configuration"></a>
</h4>
<p>This is to run the analysis on default set of values for the
supported parameters. Initially, the values are set based on the Xing et
al(2021) <span class="citation">(Xing et al. 2020)</span> and crop is
<em>Avocado</em>. This would run the workflow on global geographical
extent quickly since the crop presence is relatively low.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sensitivity_analysis</span>()</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; New analysis started for given raster</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Running sensitivity analysis for the extent: [ -24, 180, -58, 60 ],</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Link threshold:  1e-06 </span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Host density threshold:  0.00015</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; The legacy packages maptools, rgdal, and rgeos, underpinning the sp package,</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; which was just loaded, will retire in October 2023.</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Please refer to R-spatial evolution reports for details, especially</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; https://r-spatial.org/r/2023/05/15/evolution4.html.</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; It may be desirable to make the sf package available;</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; package maintainers should consider adding sf to Suggests:.</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; The sp package is now running under evolution status 2</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;      (status 2 uses the sf package in place of rgdal)</span></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Running sensitivity analysis for the extent: [ -140, -34, -58, 60 ],</span></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Link threshold:  1e-06 </span></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Host density threshold:  0.00015</span></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Running sensitivity analysis for the extent: [ -24, 180, -58, 60 ],</span></span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Link threshold:  1e-06 </span></span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Host density threshold:  2.5e-05</span></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Running sensitivity analysis for the extent: [ -140, -34, -58, 60 ],</span></span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Link threshold:  1e-06 </span></span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Host density threshold:  2.5e-05</span></span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; raster created: /var/folders/r5/zggvft9d3yn5kh51wqp78rd00000gn/T//RtmpGgGMhT/plots/mean_20231009210932.tif</span></span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a><span class="sc">|---------</span><span class="er">|</span><span class="sc">---------</span><span class="er">|</span><span class="sc">---------</span><span class="er">|</span><span class="sc">---------</span><span class="er">|</span></span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a><span class="er">===</span></span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a>                                          </span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a><span class="er">|</span><span class="sc">---------</span><span class="er">|</span><span class="sc">---------</span><span class="er">|</span><span class="sc">---------</span><span class="er">|</span><span class="sc">---------</span><span class="er">|</span></span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a><span class="er">======</span></span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a>                                          </span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; raster created: /var/folders/r5/zggvft9d3yn5kh51wqp78rd00000gn/T//RtmpGgGMhT/plots/variance_20231009210945.tif</span></span></code></pre></div>
<p><img src="analysis_files/figure-html/unnamed-chunk-5-1.png" width="700"></p>
<pre><code>#&gt; 
|---------|---------|---------|---------|
===
                                          

|---------|---------|---------|---------|
=====
                                          
#&gt; raster created: /var/folders/r5/zggvft9d3yn5kh51wqp78rd00000gn/T//RtmpGgGMhT/plots/difference_20231009210948.tif</code></pre>
<p><img src="analysis_files/figure-html/unnamed-chunk-5-2.png" width="700"></p>
<pre><code><span><span class="co">#&gt; sensitivity analysis completed. Refer to maps for results.</span></span></code></pre>
<p><img src="analysis_files/figure-html/unnamed-chunk-5-3.png" width="700"></p>
<pre><code><span><span class="co">#&gt; [1] TRUE</span></span></code></pre>
<p>The results are based on the values set for each of the parameters
which we will see in details in the next section.</p>
</div>
</div>
<div class="section level3">
<h3 id="running-new-analysis">Running new analysis<a class="anchor" aria-label="anchor" href="#running-new-analysis"></a>
</h3>
<p>We provide 2 methods or entry points to run analysis by setting new
values for the supported parameters.</p>
<div class="section level4">
<h4 id="setting-values-in-a-function">Setting values in a function<a class="anchor" aria-label="anchor" href="#setting-values-in-a-function"></a>
</h4>
<p>The goal of the this function is to provide simple invasive factors
as parameters. The internal implementation and program deals with object
of <code>terra</code> <span class="citation">(Hijmans 2023)</span> and
<code>igraph</code><span class="citation">(Csardi and Nepusz
2006)</span> . The primary object is of type <code>SpatRaster</code>
from <code>terra</code> . To get started, we will use quick way to
obtain raster and later we will understand the details.</p>
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">avocado</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/cropharvest_rast.html">cropharvest_rast</a></span><span class="op">(</span><span class="st">"avocado"</span>, <span class="st">"monfreda"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># verify the raster object</span></span>
<span><span class="va">avocado</span></span>
<span><span class="co">#&gt; class       : SpatRaster </span></span>
<span><span class="co">#&gt; dimensions  : 2160, 4320, 1  (nrow, ncol, nlyr)</span></span>
<span><span class="co">#&gt; resolution  : 0.08333333, 0.08333333  (x, y)</span></span>
<span><span class="co">#&gt; extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)</span></span>
<span><span class="co">#&gt; coord. ref. : lon/lat WGS 84 (EPSG:4326) </span></span>
<span><span class="co">#&gt; source      : avocado_HarvestedAreaFraction.tif </span></span>
<span><span class="co">#&gt; name        : avocado_HarvestedAreaFraction</span></span>
<span><span class="fu">terra</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/terra/man/plot.html" class="external-link">plot</a></span><span class="op">(</span><span class="va">avocado</span><span class="op">)</span></span></code></pre></div>
<p><img src="analysis_files/figure-html/unnamed-chunk-6-1.png" width="700"></p>
<p>Now that we have a raster object, it can be fed directly to the
workflow. We will only set the required parameter - <em>rast</em>. The
value represents <em>Avocado</em> plantation in geographical area of
North America.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>risk_indexes <span class="ot">&lt;-</span> <span class="fu">sean</span>(avocado)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Running sensitivity analysis for the extent: [ -24, 180, -58, 60 ],</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Link threshold:  0 </span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Host density threshold:  0</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Running sensitivity analysis for the extent: [ -140, -34, -58, 60 ],</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Link threshold:  0 </span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Host density threshold:  0</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; raster created: /var/folders/r5/zggvft9d3yn5kh51wqp78rd00000gn/T//RtmpGgGMhT/plots/mean_20231009211012.tif</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a><span class="sc">|---------</span><span class="er">|</span><span class="sc">---------</span><span class="er">|</span><span class="sc">---------</span><span class="er">|</span><span class="sc">---------</span><span class="er">|</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a><span class="er">===</span></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>                                          </span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a><span class="er">|</span><span class="sc">---------</span><span class="er">|</span><span class="sc">---------</span><span class="er">|</span><span class="sc">---------</span><span class="er">|</span><span class="sc">---------</span><span class="er">|</span></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a><span class="er">======</span></span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>                                          </span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; raster created: /var/folders/r5/zggvft9d3yn5kh51wqp78rd00000gn/T//RtmpGgGMhT/plots/variance_20231009211015.tif</span></span></code></pre></div>
<p><img src="analysis_files/figure-html/unnamed-chunk-7-1.png" width="700"></p>
<pre><code>#&gt; 
|---------|---------|---------|---------|
===
                                          

|---------|---------|---------|---------|
=====
                                          
#&gt; raster created: /var/folders/r5/zggvft9d3yn5kh51wqp78rd00000gn/T//RtmpGgGMhT/plots/difference_20231009211017.tif</code></pre>
<p><img src="analysis_files/figure-html/unnamed-chunk-7-2.png" width="700"><img src="analysis_files/figure-html/unnamed-chunk-7-3.png" width="700"></p>
<p>The results should be interpreted in accordance to the values of
other parameters that have factored as arguments to <code>sean</code>.
Run ?sean to see all the supported parameters. We will later see the
usage of other parameters as well.</p>
<ol style="list-style-type: decimal">
<li><p>rast - <em>spatRaster</em>. Represents map of crop presence in a
geographical area.</p></li>
<li><p>geoscale - <em>Vector</em>. Geographical coordinates in the form
of c(Xmin, Xmax, Ymin, Ymax)</p></li>
<li>
<p>global - <em>Logical</em>. When set to TRUE, geoscale is
ignored.</p>
<ul>
<li>
<p>Get geographical scales used in global analysis -</p>
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="../reference/global_scales.html">global_scales</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt; $east</span></span>
<span><span class="co">#&gt; [1] -24 180 -58  60</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; $west</span></span>
<span><span class="co">#&gt; [1] -140  -34  -58   60</span></span></code></pre></div>
</li>
<li>
<p>Although recommended not to change the global scales since it has
been finalized after several tries. Still, for advance use, set the
global geographic scales using -</p>
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co">#set_global_scales(list(east = c(-24, 180, -58, 60), west = c(-140, -34, -58, 60)))</span></span></code></pre></div>
</li>
</ul>
</li>
</ol>
</div>
<div class="section level4">
<h4 id="using-configuration">Using configuration<a class="anchor" aria-label="anchor" href="#using-configuration"></a>
</h4>
<p>More parameters are available under configuration and thus more
control over the analysis. The configuration file name is
<code>parameters.yaml</code>, currently supporting up to 10 parameters.
The intuition behind this methodology is to provide a basic interface
for setting new values. The snippet below describes the basic usage of
configuration.</p>
<p>Get the initial configuration file. By default this function will
save the file in temporary directory <code><a href="https://rdrr.io/r/base/tempfile.html" class="external-link">tempdir()</a></code>, however we
recommend saving path where program will have write permissions. Using
<em>iwindow = TRUE</em> will prompt a selection window to save config
file.</p>
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">config_file</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/get_parameters.html">get_parameters</a></span><span class="op">(</span>out_path <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/tempfile.html" class="external-link">tempdir</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] "parameters fetched successfully"</span></span>
<span><span class="va">config_file</span></span>
<span><span class="co">#&gt; [1] "/var/folders/r5/zggvft9d3yn5kh51wqp78rd00000gn/T//RtmpGgGMhT/parameters.yaml"</span></span></code></pre></div>
<p>The file should look something like this -</p>
<div class="figure">
<img src="images/initconfig.png" width="700" alt=""><p class="caption">Initial parameters.yaml</p>
</div>
<p>The values must be modified without modifying the structure. The
order don’t matter for the program. The new values in the configuration
must be fed to the workflow using -</p>
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="../reference/set_parameters.html">set_parameters</a></span><span class="op">(</span>new_params <span class="op">=</span> <span class="va">config_file</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] TRUE</span></span>
<span><span class="co">#using iwindow = true will prompt a selction window to choose config file.</span></span></code></pre></div>
<p><code><a href="../reference/get_parameters.html">get_parameters()</a></code> was only to fetch the initial
parameters. While you can, it is not required to re-fetch. Modify the
value and feed it to workflow using <code><a href="../reference/set_parameters.html">set_parameters()</a></code>.</p>
</div>
</div>
<div class="section level3">
<h3 id="parameters">Parameters<a class="anchor" aria-label="anchor" href="#parameters"></a>
</h3>
<div class="section level4">
<h4 id="hosts">Hosts<a class="anchor" aria-label="anchor" href="#hosts"></a>
</h4>
<p>We have some helper functions to make the analysis easier. Available
sources can be seen using -</p>
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">geohabnet</span><span class="fu">::</span><span class="fu"><a href="../reference/get_supported_sources.html">get_supported_sources</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] "monfreda" "mapspam"</span></span></code></pre></div>
<p>More specifically, we support 2 data set sources - <a href="http://www.earthstat.org/harvested-area-yield-175-crops/" class="external-link">Monfreda</a>
and <a href="https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/PRFF8V" class="external-link">Mapspam</a>
using the APIs provided by <a href="https://CRAN.R-project.org/package=geodata" class="external-link">Geodata</a>. These
sources have crop presence in the geographical areas in the form of
raster(tiff). To start with, we can check if a certain crop is available
in the source -</p>
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="../reference/search_crop.html">search_crop</a></span><span class="op">(</span><span class="st">"avocado"</span><span class="op">)</span> <span class="co">#1</span></span>
<span><span class="co">#&gt; [1] "monfreda"</span></span>
<span><span class="fu"><a href="../reference/search_crop.html">search_crop</a></span><span class="op">(</span><span class="st">"banana"</span><span class="op">)</span> <span class="co">#2</span></span>
<span><span class="co">#&gt; [1] "monfreda" "spam"</span></span></code></pre></div>
<p>The #1 result suggests that we have crop information available under
<code>monfreda</code> . Now, #2 suggests that <em>banana</em> is present
in 2 sources. We will use the results from here to obtain its raster
data from the one of the specified sources.</p>
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># get avocado data</span></span>
<span><span class="va">rast_avocado</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/crops_rast.html">crops_rast</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/list.html" class="external-link">list</a></span><span class="op">(</span>monfreda <span class="op">=</span> <span class="st">"avocado"</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co">#get data of banana crop</span></span>
<span><span class="va">rast_ban</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/crops_rast.html">crops_rast</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/list.html" class="external-link">list</a></span><span class="op">(</span>mapspam <span class="op">=</span> <span class="st">"banana"</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<p>The returned is actually if type <code>SpatRaster</code>. In above,
we will have seperate raster information for each of the crop. Crops can
be combined and be returned as one raster.</p>
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">rast_avo_ban</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/crops_rast.html">crops_rast</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/list.html" class="external-link">list</a></span><span class="op">(</span>monfreda <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="st">"avocado"</span>, <span class="st">"banana"</span><span class="op">)</span>, mapspam <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="st">"banana"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<p>In this case for <em>banana</em>, information from all the sources
will be first combined using mean and then all the crop information
i.e. banana and avocado both are again combined into one raster. This is
done to produce a single map which contains information of all the
requested crops. We have one more method to obtain raster, using
<em>tiff -</em> <code><a href="../reference/tiff_torast.html">tiff_torast()</a></code> . Finally, we have
<code><a href="../reference/get_rasters.html">get_rasters()</a></code> method, which is an abstraction of . To see
the difference in data that was generated in last 3 methods -</p>
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">results</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html" class="external-link">lapply</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/list.html" class="external-link">list</a></span><span class="op">(</span><span class="va">rast_avocado</span>, <span class="va">rast_ban</span>, <span class="va">rast_avo_ban</span><span class="op">)</span>, <span class="fu">terra</span><span class="fu">::</span><span class="va"><a href="https://rdrr.io/pkg/terra/man/rast.html" class="external-link">rast</a></span><span class="op">)</span></span></code></pre></div>
<p>The result obtained from one of these methods can be used as an
argument to <code><a href="../reference/sean.html">sean()</a></code> . Value of <code>results</code> is list
of risk indices.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="fu">list</span>(rast_avocado, rast_ban, rast_avo_ban), sean)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Running sensitivity analysis for the extent: [ -24, 180, -58, 60 ],</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Link threshold:  0 </span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Host density threshold:  0</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Running sensitivity analysis for the extent: [ -140, -34, -58, 60 ],</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Link threshold:  0 </span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Host density threshold:  0</span></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; raster created: /var/folders/r5/zggvft9d3yn5kh51wqp78rd00000gn/T//RtmpGgGMhT/plots/mean_20231009211706.tif</span></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a><span class="sc">|---------</span><span class="er">|</span><span class="sc">---------</span><span class="er">|</span><span class="sc">---------</span><span class="er">|</span><span class="sc">---------</span><span class="er">|</span></span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a><span class="er">===</span></span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>                                          </span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a><span class="er">|</span><span class="sc">---------</span><span class="er">|</span><span class="sc">---------</span><span class="er">|</span><span class="sc">---------</span><span class="er">|</span><span class="sc">---------</span><span class="er">|</span></span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a><span class="er">=====</span></span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a>                                          </span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; raster created: /var/folders/r5/zggvft9d3yn5kh51wqp78rd00000gn/T//RtmpGgGMhT/plots/variance_20231009211710.tif</span></span></code></pre></div>
<p><img src="analysis_files/figure-html/unnamed-chunk-17-1.png" width="700"></p>
<pre><code>#&gt; 
|---------|---------|---------|---------|
===
                                          

|---------|---------|---------|---------|
=====
                                          
#&gt; raster created: /var/folders/r5/zggvft9d3yn5kh51wqp78rd00000gn/T//RtmpGgGMhT/plots/difference_20231009211714.tif</code></pre>
<p><img src="analysis_files/figure-html/unnamed-chunk-17-2.png" width="700"></p>
<pre><code><span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Running sensitivity analysis for the extent: [ -24, 180, -58, 60 ],</span></span>
<span><span class="co">#&gt;  Link threshold:  0 </span></span>
<span><span class="co">#&gt;  Host density threshold:  0</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Running sensitivity analysis for the extent: [ -140, -34, -58, 60 ],</span></span>
<span><span class="co">#&gt;  Link threshold:  0 </span></span>
<span><span class="co">#&gt;  Host density threshold:  0</span></span>
<span><span class="co">#&gt; raster created: /var/folders/r5/zggvft9d3yn5kh51wqp78rd00000gn/T//RtmpGgGMhT/plots/mean_20231009211720.tif</span></span></code></pre>
<p><img src="analysis_files/figure-html/unnamed-chunk-17-3.png" width="700"></p>
<pre><code>#&gt; 
|---------|---------|---------|---------|
===
                                          

|---------|---------|---------|---------|
=====
                                          
#&gt; raster created: /var/folders/r5/zggvft9d3yn5kh51wqp78rd00000gn/T//RtmpGgGMhT/plots/variance_20231009211724.tif</code></pre>
<p><img src="analysis_files/figure-html/unnamed-chunk-17-4.png" width="700"></p>
<pre><code>#&gt; 
|---------|---------|---------|---------|
==
                                          

|---------|---------|---------|---------|
=====
                                          
#&gt; raster created: /var/folders/r5/zggvft9d3yn5kh51wqp78rd00000gn/T//RtmpGgGMhT/plots/difference_20231009211726.tif</code></pre>
<p><img src="analysis_files/figure-html/unnamed-chunk-17-5.png" width="700"></p>
<pre><code><span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Running sensitivity analysis for the extent: [ -24, 180, -58, 60 ],</span></span>
<span><span class="co">#&gt;  Link threshold:  0 </span></span>
<span><span class="co">#&gt;  Host density threshold:  0</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Running sensitivity analysis for the extent: [ -140, -34, -58, 60 ],</span></span>
<span><span class="co">#&gt;  Link threshold:  0 </span></span>
<span><span class="co">#&gt;  Host density threshold:  0</span></span>
<span><span class="co">#&gt; raster created: /var/folders/r5/zggvft9d3yn5kh51wqp78rd00000gn/T//RtmpGgGMhT/plots/mean_20231009211804.tif</span></span></code></pre>
<p><img src="analysis_files/figure-html/unnamed-chunk-17-6.png" width="700"></p>
<pre><code>#&gt; 
|---------|---------|---------|---------|
==
                                          

|---------|---------|---------|---------|
=====
                                          
#&gt; raster created: /var/folders/r5/zggvft9d3yn5kh51wqp78rd00000gn/T//RtmpGgGMhT/plots/variance_20231009211807.tif</code></pre>
<p><img src="analysis_files/figure-html/unnamed-chunk-17-7.png" width="700"></p>
<pre><code>#&gt; 
|---------|---------|---------|---------|
==
                                          

|---------|---------|---------|---------|
=====
                                          
#&gt; raster created: /var/folders/r5/zggvft9d3yn5kh51wqp78rd00000gn/T//RtmpGgGMhT/plots/difference_20231009211810.tif</code></pre>
<p><img src="analysis_files/figure-html/unnamed-chunk-17-8.png" width="700"><img src="analysis_files/figure-html/unnamed-chunk-17-9.png" width="700"></p>
<p>So far, we have now run the sensitivity analysis workflow for avocado
and banana on global scale and default set of parameter values.
Alternatively, we can just specify the crops under
<code>parameters.yaml</code> and run the workflow -</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">sensitivity_analysis</span>()</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; New analysis started for given raster</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Running sensitivity analysis for the extent: [ -24, 180, -58, 60 ],</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Link threshold:  1e-06 </span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Host density threshold:  0.00015</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Running sensitivity analysis for the extent: [ -140, -34, -58, 60 ],</span></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Link threshold:  1e-06 </span></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Host density threshold:  0.00015</span></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Running sensitivity analysis for the extent: [ -24, 180, -58, 60 ],</span></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Link threshold:  1e-06 </span></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Host density threshold:  2.5e-05</span></span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Running sensitivity analysis for the extent: [ -140, -34, -58, 60 ],</span></span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Link threshold:  1e-06 </span></span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Host density threshold:  2.5e-05</span></span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; raster created: /var/folders/r5/zggvft9d3yn5kh51wqp78rd00000gn/T//RtmpGgGMhT/plots/mean_20231009211825.tif</span></span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb29-21"><a href="#cb29-21" aria-hidden="true" tabindex="-1"></a><span class="sc">|---------</span><span class="er">|</span><span class="sc">---------</span><span class="er">|</span><span class="sc">---------</span><span class="er">|</span><span class="sc">---------</span><span class="er">|</span></span>
<span id="cb29-22"><a href="#cb29-22" aria-hidden="true" tabindex="-1"></a><span class="er">===</span></span>
<span id="cb29-23"><a href="#cb29-23" aria-hidden="true" tabindex="-1"></a>                                          </span>
<span id="cb29-24"><a href="#cb29-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-25"><a href="#cb29-25" aria-hidden="true" tabindex="-1"></a><span class="er">|</span><span class="sc">---------</span><span class="er">|</span><span class="sc">---------</span><span class="er">|</span><span class="sc">---------</span><span class="er">|</span><span class="sc">---------</span><span class="er">|</span></span>
<span id="cb29-26"><a href="#cb29-26" aria-hidden="true" tabindex="-1"></a><span class="er">======</span></span>
<span id="cb29-27"><a href="#cb29-27" aria-hidden="true" tabindex="-1"></a>                                          </span>
<span id="cb29-28"><a href="#cb29-28" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; raster created: /var/folders/r5/zggvft9d3yn5kh51wqp78rd00000gn/T//RtmpGgGMhT/plots/variance_20231009211828.tif</span></span></code></pre></div>
<p><img src="analysis_files/figure-html/unnamed-chunk-18-1.png" width="700"></p>
<pre><code>#&gt; 
|---------|---------|---------|---------|
===
                                          

|---------|---------|---------|---------|
======
                                          
#&gt; raster created: /var/folders/r5/zggvft9d3yn5kh51wqp78rd00000gn/T//RtmpGgGMhT/plots/difference_20231009211831.tif</code></pre>
<p><img src="analysis_files/figure-html/unnamed-chunk-18-2.png" width="700"></p>
<pre><code><span><span class="co">#&gt; sensitivity analysis completed. Refer to maps for results.</span></span></code></pre>
<p><img src="analysis_files/figure-html/unnamed-chunk-18-3.png" width="700"></p>
</div>
<div class="section level4">
<h4 id="thresholds">Thresholds<a class="anchor" aria-label="anchor" href="#thresholds"></a>
</h4>
<p>Thresholds are used to select subset of values from the
<code>SpatRaster</code> on which the operations are applied. It directly
effects the connectivity and gives a sense of sensitivity in the
network. The intermediate goal is to produce a adjacency graph which
essentially determines the connectivity. Cells which doesn’t meet the
threshold are removed from the consideration by dispersal models.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>risk_indexes <span class="ot">&lt;-</span> <span class="fu">sean</span>(avocado, <span class="at">host_density_threshold =</span> <span class="fl">0.00001</span>, <span class="at">link_threshold =</span> <span class="fl">0.00001</span>)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Running sensitivity analysis for the extent: [ -24, 180, -58, 60 ],</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Link threshold:  1e-05 </span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Host density threshold:  1e-05</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Running sensitivity analysis for the extent: [ -140, -34, -58, 60 ],</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Link threshold:  1e-05 </span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Host density threshold:  1e-05</span></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; raster created: /var/folders/r5/zggvft9d3yn5kh51wqp78rd00000gn/T//RtmpGgGMhT/plots/mean_20231009211839.tif</span></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a><span class="sc">|---------</span><span class="er">|</span><span class="sc">---------</span><span class="er">|</span><span class="sc">---------</span><span class="er">|</span><span class="sc">---------</span><span class="er">|</span></span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a><span class="er">===</span></span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>                                          </span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a><span class="er">|</span><span class="sc">---------</span><span class="er">|</span><span class="sc">---------</span><span class="er">|</span><span class="sc">---------</span><span class="er">|</span><span class="sc">---------</span><span class="er">|</span></span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a><span class="er">======</span></span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a>                                          </span>
<span id="cb32-19"><a href="#cb32-19" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; raster created: /var/folders/r5/zggvft9d3yn5kh51wqp78rd00000gn/T//RtmpGgGMhT/plots/variance_20231009211842.tif</span></span></code></pre></div>
<p><img src="analysis_files/figure-html/unnamed-chunk-19-1.png" width="700"></p>
<pre><code>#&gt; 
|---------|---------|---------|---------|
===
                                          

|---------|---------|---------|---------|
======
                                          
#&gt; raster created: /var/folders/r5/zggvft9d3yn5kh51wqp78rd00000gn/T//RtmpGgGMhT/plots/difference_20231009211845.tif</code></pre>
<p><img src="analysis_files/figure-html/unnamed-chunk-19-2.png" width="700"><img src="analysis_files/figure-html/unnamed-chunk-19-3.png" width="700"></p>
<div class="section level5">
<h5 id="density-thresholds">Density Thresholds<a class="anchor" aria-label="anchor" href="#density-thresholds"></a>
</h5>
<p>host density threshold. The host density threshold is the minimum
cropland proportion in the grid cells (or locations) that will be
included in the analysis. This parameter is called
<code>HostDensityThreshold</code> and supports a list of values between
0 and 1. Before running the sensitivity_analysis() function, check that
the values for the host density threshold are smaller than the maximum
host density in the map to prevent errors. The values are rounded off to
5 decimal points.</p>
</div>
<div class="section level5">
<h5 id="link-thresholds">Link Thresholds<a class="anchor" aria-label="anchor" href="#link-thresholds"></a>
</h5>
<p>Based on the information on host distribution and dispersal kernels,
adjacency matrices are created, where entries are the likelihood of
pathogen movement between locations. Then, adjacency matrices are
converted into graph objects to perform a network analysis, where the
entries in the adjacency matrices now are the weight of the links of the
network.</p>
<p>Choosing link weight thresholds helps to focus the analysis on the
more likely pathogen dispersal in the landscape.</p>
<p>Like what you did with the host density threshold, you can provide a
list of positive values to <code>LinkThreshold</code>. Before running
the sensitivity_analysis() function, check that the values for the link
weight threshold are smaller than the maximum link weight in the network
to prevent errors.</p>
</div>
</div>
<div class="section level4">
<h4 id="aggregation">Aggregation<a class="anchor" aria-label="anchor" href="#aggregation"></a>
</h4>
<p>Aggregation strategy refers to the function used to create a new map
of host density with a lower resolution (larger cells). Reducing the
spatial resolution helps to reduce the computational power needed to run
the analysis.</p>
<ul>
<li><p>If AggregationStrategy: [sum], then the sum of the cropland
proportion of all initially small grids within a large grid is divided
by the total number of initially small grids within that large
grid.</p></li>
<li><p>If AggregationStrategy: [mean], then the sum of the cropland
proportion of all initially small grids within a large grid is divided
by the total number of initially small grids containing only land (where
small grids with water are excluded) within that large grid.</p></li>
</ul>
<p>By default, analysis is run on both but can be opted out from one. If
only one method is used, then the difference map is skipped from the
outcome.</p>
</div>
<div class="section level4">
<h4 id="distance-methods">Distance methods<a class="anchor" aria-label="anchor" href="#distance-methods"></a>
</h4>
<p>For each pair of locations in the host map with values greater than
the host density threshold, the sensitivity_analysis() function will
calculate the physical distances and use them to calculate the relative
likelihood of pathogen movement between locations based on their
pairwise geographical proximity.</p>
<p>There are two different options to calculate the distance between
locations.</p>
<p>· Vincenty ellipsoid distance</p>
<p>This option is highly accurate but more computationally
expensive.</p>
<p>· Geodesic distance</p>
<p>This option is less computationally expensive and less accurate than
the option above.</p>
<p>You can set the distance option either as DistanceStrategy:
“vincentyEllipsoid” or DistanceStrategy: “geodesic”. One of these
options should be used as input to run the analysis. You can check
supported methods in analysis by running <code><a href="../reference/dist_methods.html">dist_methods()</a></code> in
the console.</p>
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="../reference/dist_methods.html">dist_methods</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] "geodesic"          "vincentyellipsoid"</span></span></code></pre></div>
</div>
<div class="section level4">
<h4 id="resolution">Resolution<a class="anchor" aria-label="anchor" href="#resolution"></a>
</h4>
<p>The aggregation factor or granularity is the number of small grid
cells that are aggregated into larger grid cells in each direction
(horizontally and vertically). The finest value is 1 which can require
analysis to run up to hours because of large number of cells in
<code>SpatRaster</code> . The resolution is also used in calculation of
variance while dis-aggregating the risk indices into coarser resolution
for producing maps.</p>
<p>If not provided, the defaulted value is selected from
<code><a href="../reference/reso.html">reso()</a></code></p>
</div>
<div class="section level4">
<h4 id="metrics">Metrics<a class="anchor" aria-label="anchor" href="#metrics"></a>
</h4>
<p>See available metrics using</p>
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="../reference/supported_metrics.html">supported_metrics</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] "betweeness"               "node_strength"           </span></span>
<span><span class="co">#&gt; [3] "sum_of_nearest_neighbors" "eigenvector_centrality"  </span></span>
<span><span class="co">#&gt; [5] "closeness"                "degree"                  </span></span>
<span><span class="co">#&gt; [7] "page_rank"</span></span></code></pre></div>
<p>Metrics corresponding to dispersal models are applied to distance
matrix with specified weights. The weights must be specified in % and
sum of all the weights should be equal to 100. We use functions from
<span class="citation">(Csardi and Nepusz 2006)</span> to calculate
metrics for each dispersal model. The 2 dispersal models that are
applied to parameters <em>inverse power law</em> and <em>negative
exponential</em>. More formally, metrics are way to determine
connectivity among nodes in a network.</p>
</div>
<div class="section level4">
<h4 id="geographical-extent">Geographical Extent<a class="anchor" aria-label="anchor" href="#geographical-extent"></a>
</h4>
<p>Geographical extent is a subset of world map defined by coordinate
reference system. The corresponding parameter to set the area in
<code><a href="../reference/sean.html">sean()</a></code> and <code>sensitivity_analyis()</code> is
<code>geoscale</code> and <code>GeoExtent</code> respectively. Default
setting is <code>global = TRUE</code> which will ignore the value of
<code>geoscale</code>. This will consider take the world map into
account using values from <code><a href="../reference/global_scales.html">global_scales()</a></code> .</p>
<ol style="list-style-type: decimal">
<li>
<p>Using function</p>
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">results</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/sean.html">sean</a></span><span class="op">(</span><span class="va">avocado</span>, global <span class="op">=</span> <span class="cn">FALSE</span>, geoscale <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">115</span>, <span class="op">-</span><span class="fl">75</span>, <span class="fl">5</span>, <span class="fl">32</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Running sensitivity analysis for the extent: [ -115, -75, 5, 32 ],</span></span>
<span><span class="co">#&gt;  Link threshold:  0 </span></span>
<span><span class="co">#&gt;  Host density threshold:  0</span></span>
<span><span class="co">#&gt; raster created: /var/folders/r5/zggvft9d3yn5kh51wqp78rd00000gn/T//RtmpGgGMhT/plots/mean_20231009211851.tif</span></span>
<span><span class="co">#&gt; raster created: /var/folders/r5/zggvft9d3yn5kh51wqp78rd00000gn/T//RtmpGgGMhT/plots/variance_20231009211851.tif</span></span></code></pre></div>
<p><img src="analysis_files/figure-html/non-global-1.png" width="700"></p>
<pre><code><span><span class="co">#&gt; raster created: /var/folders/r5/zggvft9d3yn5kh51wqp78rd00000gn/T//RtmpGgGMhT/plots/difference_20231009211852.tif</span></span></code></pre>
<p><img src="analysis_files/figure-html/non-global-2.png" width="700"><img src="analysis_files/figure-html/non-global-3.png" width="700"></p>
</li>
<li>
<p>Using config</p>
<p>Set <code>Global = FALSE</code> and
<code>CustomExt = [-115, -75, 5, 32]</code> . The initial
<code>parameters.yaml</code> already contains this value which would run
in combination with other parameters.</p>
</li>
</ol>
<p>When provided with <code>geoscale</code>, program will take the
subset of provided raster (dataset of crop). The workflow will apply
graph operations and network connectivity only to the subset.</p>
</div>
</div>
<div class="section level3">
<h3 id="outputs">Outputs<a class="anchor" aria-label="anchor" href="#outputs"></a>
</h3>
<p>By default, 3 maps are produced for each analysis.
<code><a href="../reference/sean.html">sean()</a></code> also returns list of risk indexes which are then fed
to <code><a href="../reference/connectivity.html">connectivity()</a></code> . This flexibility is supposed to allow
users to use the risk indexes for their purposes or use our function to
produce maps with further different parameters.</p>
<p>In a code below, after obtaining results, the maps are produced. In
order to produce calculate variance, cells of <code>SpatRaster</code> is
extended to coarser value using <code>res</code> parameter. Setting
<code>maps = FALSE</code> will suppress the calculation of outputs.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>risk_indexes <span class="ot">&lt;-</span> <span class="fu">sean</span>(avocado)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Running sensitivity analysis for the extent: [ -24, 180, -58, 60 ],</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Link threshold:  0 </span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Host density threshold:  0</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Running sensitivity analysis for the extent: [ -140, -34, -58, 60 ],</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Link threshold:  0 </span></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Host density threshold:  0</span></span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; raster created: /var/folders/r5/zggvft9d3yn5kh51wqp78rd00000gn/T//RtmpGgGMhT/plots/mean_20231009211913.tif</span></span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a><span class="sc">|---------</span><span class="er">|</span><span class="sc">---------</span><span class="er">|</span><span class="sc">---------</span><span class="er">|</span><span class="sc">---------</span><span class="er">|</span></span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a><span class="er">===</span></span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a>                                          </span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-16"><a href="#cb38-16" aria-hidden="true" tabindex="-1"></a><span class="er">|</span><span class="sc">---------</span><span class="er">|</span><span class="sc">---------</span><span class="er">|</span><span class="sc">---------</span><span class="er">|</span><span class="sc">---------</span><span class="er">|</span></span>
<span id="cb38-17"><a href="#cb38-17" aria-hidden="true" tabindex="-1"></a><span class="er">======</span></span>
<span id="cb38-18"><a href="#cb38-18" aria-hidden="true" tabindex="-1"></a>                                          </span>
<span id="cb38-19"><a href="#cb38-19" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; raster created: /var/folders/r5/zggvft9d3yn5kh51wqp78rd00000gn/T//RtmpGgGMhT/plots/variance_20231009211916.tif</span></span></code></pre></div>
<p><img src="analysis_files/figure-html/unnamed-chunk-22-1.png" width="700"></p>
<pre><code>#&gt; 
|---------|---------|---------|---------|
===
                                          

|---------|---------|---------|---------|
======
                                          
#&gt; raster created: /var/folders/r5/zggvft9d3yn5kh51wqp78rd00000gn/T//RtmpGgGMhT/plots/difference_20231009211919.tif</code></pre>
<p><img src="analysis_files/figure-html/unnamed-chunk-22-2.png" width="700"><img src="analysis_files/figure-html/unnamed-chunk-22-3.png" width="700"></p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">connectivity</span>(risk_indexes)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; raster created: /var/folders/r5/zggvft9d3yn5kh51wqp78rd00000gn/T//RtmpGgGMhT/plots/mean_20231009211921.tif</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="sc">|---------</span><span class="er">|</span><span class="sc">---------</span><span class="er">|</span><span class="sc">---------</span><span class="er">|</span><span class="sc">---------</span><span class="er">|</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a><span class="er">===</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>                                          </span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a><span class="er">|</span><span class="sc">---------</span><span class="er">|</span><span class="sc">---------</span><span class="er">|</span><span class="sc">---------</span><span class="er">|</span><span class="sc">---------</span><span class="er">|</span></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a><span class="er">======</span></span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>                                          </span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; raster created: /var/folders/r5/zggvft9d3yn5kh51wqp78rd00000gn/T//RtmpGgGMhT/plots/variance_20231009211924.tif</span></span></code></pre></div>
<p><img src="analysis_files/figure-html/unnamed-chunk-22-4.png" width="700"></p>
<pre><code>#&gt; 
|---------|---------|---------|---------|
===
                                          

|---------|---------|---------|---------|
======
                                          
#&gt; raster created: /var/folders/r5/zggvft9d3yn5kh51wqp78rd00000gn/T//RtmpGgGMhT/plots/difference_20231009211926.tif</code></pre>
<p><img src="analysis_files/figure-html/unnamed-chunk-22-5.png" width="700"><img src="analysis_files/figure-html/unnamed-chunk-22-6.png" width="700"></p>
<p>is equivalent to <code><a href="../reference/sensitivity_analysis.html">sensitivity_analysis()</a></code> .</p>
<p>The final operations are performed risk indices and on the 3 results
that are produced -</p>
<ol style="list-style-type: decimal">
<li>
<p>Mean</p>
<p>Simply a mean of all the <code>SpatRasters</code> resulting from
combination of parameter values. The values in cells are added across
all the indices and divided by number of indices.</p>
</li>
<li>
<p>Variance</p>
<p>Uses <code><a href="https://rdrr.io/r/stats/cor.html" class="external-link">stats::var</a></code> on risk indices, subset is extracted for
provided scale and finally pixels are dis-aggregated using <em>factor =
resolution value in original parameter</em> to from previous
step.</p>
</li>
<li>
<p>Difference</p>
<p>If both the aggregation methods (<em>sum and mean</em>) is selected,
then difference is calculated between the rank of matrices which are
essentially numeric cells of risk indices of type <em>SpatRaster</em>.
The result is dis-aggregated in the same way as previous step.</p>
</li>
</ol>
<p>Set <em>pmean, pvar, pdiff</em> to <em>FALSE</em> to skip the any of
the calculation in <code><a href="../reference/connectivity.html">connectivity()</a></code> to skip this calculation.
In <code><a href="../reference/sean.html">sean()</a></code> or <code><a href="../reference/sensitivity_analysis.html">sensitivity_analysis()</a></code>, set
<code>map = FALSE</code> to skip the generation of maps as an outcome.
In case of global analysis, result of eastern and western geographic
extents are merged using <code><a href="https://rdrr.io/pkg/terra/man/merge.html" class="external-link">terra::merge()</a></code> . The outcome of
each of the operation are saved in the new directory <em>plots</em>
under the specified path in <code>OutDir</code> with name
<em>opt_datetime.tif</em>, where <em>opt</em> is one of the above
suffixed by datetime of the file created. If the <code>outdir</code> is
empty, the value is defaulted to <code><a href="https://rdrr.io/r/base/tempfile.html" class="external-link">tempdir()</a></code> . This applies
to correponding parameter <code>outdir</code> in all the functions.</p>
<div class="section level4">
<h4 class="unnumbered" id="references">References<a class="anchor" aria-label="anchor" href="#references"></a>
</h4>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-config" class="csl-entry">
Allaire, JJ. 2023. <span>“Config: Manage Environment Specific
Configuration Values.”</span> <a href="https://CRAN.R-project.org/package=config" class="external-link">https://CRAN.R-project.org/package=config</a>.
</div>
<div id="ref-igraph" class="csl-entry">
Csardi, Gabor, and Tamas Nepusz. 2006. <span>“The Igraph Software
Package for Complex Network Research”</span> Complex Systems: 1695. <a href="https://igraph.org" class="external-link">https://igraph.org</a>.
</div>
<div id="ref-terra" class="csl-entry">
Hijmans, Robert J. 2023. <span>“Terra: Spatial Data Analysis.”</span> <a href="https://CRAN.R-project.org/package=terra" class="external-link">https://CRAN.R-project.org/package=terra</a>.
</div>
<div id="ref-internationalfoodpolicyresearchinstitute2019" class="csl-entry">
International Food Policy Research Institute. 2019. <span>“Global
Spatially-Disaggregated Crop Production Statistics Data for 2010 Version
2.0.”</span> Harvard Dataverse. <a href="https://doi.org/10.7910/DVN/PRFF8V" class="external-link">https://doi.org/10.7910/DVN/PRFF8V</a>.
</div>
<div id="ref-sre_book" class="csl-entry">
Majors, Charity. 2022. <em>SRE Workbook: Configuration Design</em>.
Google. <a href="https://sre.google/workbook/configuration-design/" class="external-link">https://sre.google/workbook/configuration-design/</a>.
</div>
<div id="ref-monfreda2008" class="csl-entry">
Monfreda, Chad, Navin Ramankutty, and Jonathan A. Foley. 2008.
<span>“Farming the Planet: 2. Geographic Distribution of Crop Areas,
Yields, Physiological Types, and Net Primary Production in the Year
2000.”</span> <em>Global Biogeochemical Cycles</em> 22 (1): n/a–. <a href="https://doi.org/10.1029/2007gb002947" class="external-link">https://doi.org/10.1029/2007gb002947</a>.
</div>
<div id="ref-nash2009" class="csl-entry">
Nash, Brent, and Martha DeMore. 2009. <span>“Using XML
Configuration-Driven Development to Create a Customizable Ground Data
System.”</span> <em>2009 IEEE Aerospace Conference</em>, March. <a href="https://doi.org/10.1109/aero.2009.4839708" class="external-link">https://doi.org/10.1109/aero.2009.4839708</a>.
</div>
<div id="ref-xing2020" class="csl-entry">
Xing, Yanru, John F Hernandez Nopsa, Kelsey F Andersen, Jorge L
Andrade-Piedra, Fenton D Beed, Guy Blomme, Mónica Carvajal-Yepes, et al.
2020. <span>“Global Cropland Connectivity: A Risk Factor for Invasion
and Saturation by Emerging Pathogens and Pests.”</span>
<em>BioScience</em> 70 (9): 744–58. <a href="https://doi.org/10.1093/biosci/biaa067" class="external-link">https://doi.org/10.1093/biosci/biaa067</a>.
</div>
</div>
</div>
</div>
</div>
  </main><aside class="col-md-3"><nav id="toc"><h2>On this page</h2>
    </nav></aside>
</div>



    <footer><div class="pkgdown-footer-left">
  <p></p>
<p>Developed by Krishna Keshav, Garrett Lab, Karen Garrett, Aaron Plex, University of Florida.</p>
</div>

<div class="pkgdown-footer-right">
  <p></p>
<p>Site built with <a href="https://pkgdown.r-lib.org/" class="external-link">pkgdown</a> 2.0.7.9000.</p>
</div>

    </footer>
</div>

  

  

  </body>
</html>
